### ISSUE TITLE
Did not work on Mac

### ISSUE THREAD

**Issue by stillfox-lee** [qwreey75/dotfiles#1]
Hi @qwreey75 , thank you for your work on this project. I found it through your share on  [reddit](https://www.reddit.com/r/vscode/comments/11e66xh/i_made_neovide_alike_cursor_effect_on_vscode/). I follow README to install and set up the **Custom CSS and JS Loader** extension in VS Code, but unfortunately it's not working for me.
Here is my setup:
```
❯ ll /usr/local/bin/code
lrwxr-xr-x  1 liaosiyi  wheel  68 11 25  2021 /usr/local/bin/code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
❯ ll /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
-rwxr-xr-x  1 liaosiyi  staff  1034  3  1 18:20 /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
❯ ll /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
-rwxr-xr-x  1 liaosiyi  staff  84768  3  1 18:39 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
❯ ll ~/Downloads/index.js
-rwxr-xr-x@ 1 liaosiyi  staff  10548  3  7 09:53 /Users/liaosiyi/Downloads/index.js
```
And here is the relevant configuration in my VS Code settings:: 
```json
    "vscode_custom_css.imports": [
        "file:///Users/liaosiyi/Downloads/index.js"
    ],
```
Could you please take a look? Thanks.

**Comment by qwreey** [comment]
![image](https://user-images.githubusercontent.com/46598063/223470597-0da151ea-277b-4c8f-ad1e-63d3bc11730f.png)
Did you enable once again after adding file? If didn't, try it!

**Comment by stillfox-lee** [comment]
> ![image](https://user-images.githubusercontent.com/46598063/223470597-0da151ea-277b-4c8f-ad1e-63d3bc11730f.png) Did you enable once again after adding file? If didn't, try it!

Yes. And I also restart vscode after execute `Enable Custom CSS and JS`.
BTW, I really like your vscode, it looks great. Which theme plugin did you use? Or did you customize it yourself?

**Comment by shihfu** [comment]
I am also having similar issues on macOS after following both the `README.md` instructions and the `Custom CSS and JS Loader` permissions configuration.

**Comment by konicyQWQ** [comment]
@stillfox-lee I am also having similar issues and I try to fix it. The reason seems like I close the minimap but the code use the minimap to check cursor coordinate.

Therefore, comment the line 212
```js
if (minimap && minimap.getBoundingClientRect().left <= newX) return
```

a pr has been merged.  #3

**Comment by stillfox-lee** [comment]
> @stillfox-lee I am also having similar issues and I try to fix it. The reason seems like I close the minimap but the code use the minimap to check cursor coordinate.
> 
> Therefore, comment the line 212
> 
> ```js
> if (minimap && minimap.getBoundingClientRect().left <= newX) return
> ```
> 
> a pr has been merged. #3

Wow! It works. Thx a lot.
