### ISSUE TITLE
no longer works on windows.

### ISSUE THREAD

**Issue by anaysharma** [qwreey75/dotfiles#2]
issue occurred after VSCode update of last month, I used [Windhawk](https://windhawk.net/) plugin called "VSCode Tweaker" to inject Javascript code into the VSCode , worked flawlessly until that update.

I tried:
- recommended method of using "custom CSS and JS loader" extension,
- clearing the VSCode cached files and folders,
- reinstalling the VSCode,
- installing VSCode insider,
- and even copy pasting the given Javascript code into the VSCode devtools console.

nothing seems to work so far, I tried to look into the given code to understand how it works with aim of try to resolve it myself, realized I don't have enough knowledge of Javascript canvas API, so was unable get far with it.

please look into the issue.

**Comment by Ngdaz** [comment]
Have the same issue with this guy, please look at this, thank you.

**Comment by anaysharma** [comment]
works after latest commit.
