### ISSUE TITLE
Text Selection Bug

### ISSUE THREAD

**Issue by lthon09** [qwreey75/dotfiles#4]
When selecting text with the cursor, the selection bugs out (The blocky text selections without any border radius aren't selected, but still show):
![imageedit_2_5893223474](https://github.com/qwreey75/dotfiles/assets/67495232/df4399e3-b477-4441-b448-222ee11bcbfd)

**Comment by qwreey** [comment]
maybe fixed...? changing the background color of .selected-text created this weird visual glitch

**Comment by lthon09** [comment]
strange...

**Comment by lthon09** [comment]
that commit didn't fix the bug, the 4 lines you deleted were fine. however, i've found the troublesome tag:
```css
.monaco-editor-background {
	background-color: transparent !important;
}
```
the editor's `background-color` has to be solid for this to not happen. you could try playing around with a color with an alpha that isn't `1` and you'll see it.
however, removing this tag would also remove the background image. maybe there's a workaround for this?

**Comment by lthon09** [comment]
it's much better to just use an extension like [this one](https://marketplace.visualstudio.com/items?itemName=shalldie.background) to change the background and remove the `.monaco-editor-background`.
