### ISSUE TITLE
The `trailCursorEffect` feature is not functioning correctly in the latest version of VSCode.

### ISSUE THREAD

**Issue by aurexav** [qwreey75/dotfiles#5]

**Comment by L0v3Iy** [comment]
mine too, 
im on linux and followed the readme file thoroughly, the extensions ran fine and able to change customize other things but the index.js just doesn't work ig

**Comment by acgxv** [comment]
This has been automatically resolved in the latest vscode.

**Comment by albert-ying** [comment]
is this still working? I tested on Version: 1.92.0 (Universal) but it seems that nothing happened after I followed the instruction...

**Comment by qwreey** [comment]
> is this still working? I tested on Version: 1.92.0 (Universal) but it seems that nothing happened after I followed the instruction...


https://github.com/user-attachments/assets/2008059d-ba2b-4b69-b124-979605fee3ef

Yes works fine
